version: "3.8"

services:
    web:
        build: .
        ports:
            - "443:443"
        volumes:
            - /etc/ssl/certs:/etc/ssl/certs:ro
            - /etc/ssl/private:/etc/ssl/private:ro
            - .:/code
