# Generated by Django 4.1.1 on 2023-04-10 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('allowsSplit', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMethods', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=255)),
                ('submerchant_id', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=3)),
                ('document_number', models.CharField(max_length=255)),
                ('document_type', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('payment_concept', models.CharField(max_length=255)),
                ('shipping_postal_code', models.CharField(max_length=10)),
                ('shipping_address', models.CharField(max_length=255)),
                ('additional_data1', models.CharField(max_length=255)),
                ('additional_data2', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('callback_url', models.URLField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('values', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='app.values')),
            ],
        ),
    ]
