# Generated by Django 4.0.4 on 2023-04-21 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_transaccion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaccion',
        ),
    ]
